const types = {

    GET_ORDER_BEGIN: 'GET_ORDER_BEGIN',
    GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS',
    GET_ORDER_FAILURE: 'GET_ORDER_FAILURE',

    GET_ORDERS_BEGIN: 'GET_ORDERS_BEGIN',
    GET_ORDERS_SUCCESS: 'GET_ORDERS_SUCCESS',
    GET_ORDERS_FAILURE: 'GET_ORDERS_FAILURE',
};
export default types;