const types = {
    CREATE_SECURE_PAY_BEGIN: 'CREATE_SECURE_PAY_BEGIN',
    CREATE_SECURE_PAY_SUCCESS: 'CREATE_SECURE_PAY_SUCCESS',
    CREATE_SECURE_PAY_FAILURE: 'CREATE_SECURE_PAY_FAILURE',

    GET_PAYMENTS_BEGIN: 'GET_PAYMENTS_BEGIN',
    GET_PAYMENTS_SUCCESS: 'GET_PAYMENTS_SUCCESS',
    GET_PAYMENTS_FAILURE: 'GET_PAYMENTS_FAILURE',

    GENERATE_REFUND_BEGIN: 'GENERATE_REFUND_BEGIN',
    GENERATE_REFUND_SUCCESS: 'GENERATE_REFUND_SUCCESS',
    GENERATE_REFUND_FAILURE: 'GENERATE_REFUND_FAILURE',

    CANCEL_AUTO_PAY_BEGIN: 'CANCEL_AUTO_PAY_BEGIN',
    CANCEL_AUTO_PAY_SUCCESS: 'CANCEL_AUTO_PAY_SUCCESS',
    CANCEL_AUTO_PAY_FAILURE: 'CANCEL_AUTO_PAY_FAILURE',

    RECURRING_AUTH_BEGIN: 'RECURRING_AUTH_BEGIN',
    RECURRING_AUTH_SUCCESS: 'RECURRING_AUTH_SUCCESS',
    RECURRING_AUTH_FAILURE: 'RECURRING_AUTH_FAILURE',

    RECURRING_PAY_BEGIN: 'RECURRING_PAY_BEGIN',
    RECURRING_PAY_SUCCESS: 'RECURRING_PAY_SUCCESS',
    RECURRING_PAY_FAILURE: 'RECURRING_PAY_FAILURE',

    APPLY_TOKEN_BEGIN: 'APPLY_TOKEN_BEGIN',
    APPLY_TOKEN_SUCCESS: 'APPLY_TOKEN_SUCCESS',
    APPLY_TOKEN_FAILURE: 'APPLY_TOKEN_FAILURE',
};
export default types;