const types = {

    GET_SUBSCRIPTION_BEGIN: 'GET_SUBSCRIPTION_BEGIN',
    GET_SUBSCRIPTION_SUCCESS: 'GET_SUBSCRIPTION_SUCCESS',
    GET_SUBSCRIPTION_FAILURE: 'GET_SUBSCRIPTION_FAILURE',
};
export default types;