const types = {
    DO_LOGIN_BEGIN: 'DO_LOGIN_BEGIN',
    DO_LOGIN_SUCCESS: 'DO_LOGIN_SUCCESS',
    DO_LOGIN_FAILURE: 'DO_LOGIN_FAILURE',

    DO_LOGOUT_BEGIN: 'DO_LOGOUT_BEGIN',
    DO_LOGOUT_SUCCESS: 'DO_LOGOUT_SUCCESS',
    DO_LOGOUT_FAILURE: 'DO_LOGOUT_FAILURE',
};
export default types;