const types = {
    GET_PRODUCTS_BEGIN: 'GET_PRODUCTS_BEGIN',
    GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
    GET_PRODUCTS_FAILURE: 'GET_PRODUCTS_FAILURE',

    GET_PRODUCT_BEGIN: 'GET_PRODUCT_BEGIN',
    GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
    GET_PRODUCT_FAILURE: 'GET_PRODUCT_FAILURE',
};
export default types;