const types = {
    ADD_TO_CART_BEGIN: 'ADD_TO_CART_BEGIN',
    ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
    ADD_TO_CART_FAILURE: 'ADD_TO_CART_FAILURE',

    UPDATE_CART_PRODUCT_BEGIN: 'UPDATE_CART_PRODUCT_BEGIN',
    UPDATE_CART_PRODUCT_SUCCESS: 'UPDATE_CART_PRODUCT_SUCCESS',
    UPDATE_CART_PRODUCT_FAILURE: 'UPDATE_CART_PRODUCT_FAILURE',

    REMOVE_CART_PRODUCT_BEGIN: 'REMOVE_CART_PRODUCT_BEGIN',
    REMOVE_CART_PRODUCT_SUCCESS: 'REMOVE_CART_PRODUCT_SUCCESS',
    REMOVE_CART_PRODUCT_FAILURE: 'REMOVE_CART_PRODUCT_FAILURE',

    GET_CART_BEGIN: 'GET_CART_BEGIN',
    GET_CART_SUCCESS: 'GET_CART_SUCCESS',
    GET_CART_FAILURE: 'GET_CART_FAILURE',

    GET_CART_MODE_BEGIN: 'GET_CART_MODE_BEGIN',
    GET_CART_MODE_SUCCESS: 'GET_CART_MODE_SUCCESS',
    GET_CART_MODE_FAILURE: 'GET_CART_MODE_FAILURE',

    INCREASE_QUANTITY_BEGIN: 'INCREASE_QUANTITY_BEGIN',
    INCREASE_QUANTITY_SUCCESS: 'INCREASE_QUANTITY_SUCCESS',
    INCREASE_QUANTITY_FAILURE: 'INCREASE_QUANTITY_FAILURE',

    DECREASE_QUANTITY_BEGIN: 'DECREASE_QUANTITY_BEGIN',
    DECREASE_QUANTITY_SUCCESS: 'DECREASE_QUANTITY_SUCCESS',
    DECREASE_QUANTITY_FAILURE: 'DECREASE_QUANTITY_FAILURE',

    SET_SHIPPING_BEGIN: 'SET_SHIPPING_BEGIN',
    SET_SHIPPING_SUCCESS: 'SET_SHIPPING_SUCCESS',
    SET_SHIPPING_FAILURE: 'SET_SHIPPING_FAILURE',

    ADD_SUBSCRIPTION_BEGIN: 'ADD_SUBSCRIPTION_BEGIN',
    ADD_SUBSCRIPTION_SUCCESS: 'ADD_SUBSCRIPTION_SUCCESS',
    ADD_SUBSCRIPTION_FAILURE: 'ADD_SUBSCRIPTION_FAILURE',
};
export default types;